### ISSUE TITLE
2018 Rewrite Roadmap

### ISSUE THREAD

**Issue by Yucked** [Yucked/Valerie#36]
<p align="center">
<img src="https://media0.giphy.com/media/3oKIP9EDlZKKFX74S4/giphy.gif" width="50%"/>
</p>

- [ ] Complete Rewrite
- [ ] Add Request Options
- [ ] Rework XP Logic

**Core Changes**
- [ ] User Webhooks
- [ ] Message Delete Event -> Save deleted messages (Guild Config)

**Feeds**
- [ ] Rewrite Reddit
- [ ] Write NSFW

**Commands**
- [ ] Profile
- [ ] Guild Config Export
- [ ] Reset Guild Config
- [ ] Public Eval
